"""
agents/github_agent.py
──────────────────────
GitHub Agent — pushes and fetches files from your GitHub repository.

FLOW (push):
  1. Authenticate with GitHub PAT
  2. Get or create the target repository
  3. Convert summary dict → formatted Markdown
  4. Create/update file in repo with commit message
  5. Return GitHub URL of the pushed file

FLOW (fetch):
  1. Authenticate
  2. Get repo
  3. Fetch file content by filename
  4. Return content to Orchestrator
"""

import os
import re
import json
import base64
from anthropic import Anthropic
from github import Github, GithubException, UnknownObjectException
from tenacity import retry, stop_after_attempt, wait_exponential

from agents.base_agent import BaseAgent
from models.schemas import Task, GitHubPushInput, GitHubFetchInput, GitHubResult
from orchestrator.memory import Memory


class GitHubAgent(BaseAgent):
    """
    Handles all GitHub operations:
      - Create repo if it doesn't exist
      - Push markdown summary files
      - Fetch files by name
      - List all files in the repo
    """

    def __init__(self, memory: Memory):
        super().__init__(memory)
        token    = os.getenv("GITHUB_TOKEN")
        username = os.getenv("GITHUB_USERNAME")
        repo     = os.getenv("GITHUB_REPO_NAME", "youtube-summaries")

        if not token or not username:
            raise EnvironmentError("GITHUB_TOKEN and GITHUB_USERNAME must be set in .env")

        self._github    = Github(token)
        self._username  = username
        self._repo_name = repo
        self._repo      = None   # Lazy-loaded on first use
        self._llm       = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    @property
    def name(self) -> str:
        return "GitHub Agent"

    # ─────────────────────────────────────────────────────────────────────────
    # MAIN ENTRY POINT (called by BaseAgent.run)
    # ─────────────────────────────────────────────────────────────────────────

    def _execute(self, task: Task) -> dict:
        """
        Routes to the correct method based on task.action.
          push         → push a summary/file to GitHub
          fetch        → retrieve a file from GitHub
          list         → list all files in the repo
          create_branch→ create a feature branch
          push_code    → push generated code to a branch
          create_pr    → open a pull request
          code_review  → review code using Claude LLM
        """
        action = task.action.lower()
        if action == "push":          return self._push(task.payload)
        elif action == "fetch":       return self._fetch(task.payload)
        elif action == "list":        return self._list_files()
        elif action == "create_branch":return self._create_branch(task.payload)
        elif action == "push_code":   return self._push_code(task.payload)
        elif action == "create_pr":   return self._create_pr(task.payload)
        elif action == "code_review": return self._code_review(task.payload)
        else:
            raise ValueError(f"Unknown GitHub action: '{action}'")

    # ─────────────────────────────────────────────────────────────────────────
    # REPO — Get or create
    # ─────────────────────────────────────────────────────────────────────────

    def _get_repo(self):
        """
        Returns the GitHub repo object.
        Creates the repo if it doesn't exist.
        Uses lazy loading — only connects to GitHub when first needed.
        """
        if self._repo:
            return self._repo

        user = self._github.get_user()
        try:
            self._repo = user.get_repo(self._repo_name)
            self.log.info(f"Connected to repo '{self._username}/{self._repo_name}'")
        except UnknownObjectException:
            self.log.warning(f"Repo '{self._repo_name}' not found — creating it...")
            self._repo = user.create_repo(
                self._repo_name,
                description="YouTube video technical summaries — generated by AI Orchestrator",
                private=False,
                auto_init=True   # Creates with a default README so it's not empty
            )
            self.log.success(f"Repo created → https://github.com/{self._username}/{self._repo_name}")

        return self._repo

    # ─────────────────────────────────────────────────────────────────────────
    # PUSH — Create or update a file in GitHub
    # ─────────────────────────────────────────────────────────────────────────

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=5))
    def _push(self, payload: dict) -> dict:
        """
        Pushes a summary file to GitHub.
        If the file already exists (same video re-processed), updates it.

        payload keys: filename, content, commit_message
        """
        inp = GitHubPushInput(**payload)
        repo = self._get_repo()

        self.log.info(f"Pushing '{inp.filename}' to GitHub...")

        try:
            # File exists — update it
            existing = repo.get_contents(inp.filename)
            result = repo.update_file(
                path=inp.filename,
                message=inp.commit_message,
                content=inp.content,
                sha=existing.sha       # Required by GitHub API for updates
            )
            action_done = "updated"

        except UnknownObjectException:
            # File doesn't exist — create it
            result = repo.create_file(
                path=inp.filename,
                message=inp.commit_message,
                content=inp.content
            )
            action_done = "created"

        github_url = result["content"].html_url
        self.log.success(f"File {action_done} → {github_url}")

        return GitHubResult(
            success=True,
            action="pushed",
            filename=inp.filename,
            url=github_url,
            message=f"File {action_done} successfully at {github_url}"
        ).model_dump()

    # ─────────────────────────────────────────────────────────────────────────
    # FETCH — Retrieve a file from GitHub
    # ─────────────────────────────────────────────────────────────────────────

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=5))
    def _fetch(self, payload: dict) -> dict:
        """
        Fetches a file's content from GitHub by filename.
        payload keys: filename
        """
        inp = GitHubFetchInput(**payload)
        repo = self._get_repo()

        self.log.info(f"Fetching '{inp.filename}' from GitHub...")

        try:
            file_obj = repo.get_contents(inp.filename)
            # GitHub returns content as base64 — decode it
            content = base64.b64decode(file_obj.content).decode("utf-8")
            self.log.success(f"File fetched — {len(content)} characters")

            return GitHubResult(
                success=True,
                action="fetched",
                filename=inp.filename,
                url=file_obj.html_url,
                content=content,
                message=f"File fetched from {file_obj.html_url}"
            ).model_dump()

        except UnknownObjectException:
            raise FileNotFoundError(
                f"File '{inp.filename}' not found in repo '{self._repo_name}'"
            )

    # ─────────────────────────────────────────────────────────────────────────
    # LIST — Show all files in the repo
    # ─────────────────────────────────────────────────────────────────────────

    def _list_files(self) -> dict:
        """Returns a list of all files in the root of the repo."""
        repo = self._get_repo()
        contents = repo.get_contents("")
        files = [
            {"name": f.name, "url": f.html_url, "size_bytes": f.size}
            for f in contents
            if f.type == "file"
        ]
        self.log.success(f"Found {len(files)} file(s) in repo")
        return {"files": files, "count": len(files)}

    # ─────────────────────────────────────────────────────────────────────────
    # CREATE BRANCH — Creates a feature branch from main
    # ─────────────────────────────────────────────────────────────────────────

    def _create_branch(self, payload: dict) -> dict:
        """
        Creates a new git branch from main.
        payload: {branch_name: "feature/SCRUM-42-user-login"}
        """
        branch_name = payload.get("branch_name", "")
        if not branch_name:
            raise ValueError("branch_name is required")

        repo = self._get_repo()
        self.log.info(f"Creating branch '{branch_name}' from main...")

        try:
            main = repo.get_branch("main")
        except Exception:
            main = repo.get_branch("master")

        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=main.commit.sha
        )
        self.log.success(f"Branch created → {branch_name}")
        return {"branch_name": branch_name, "message": f"Branch '{branch_name}' created"}

    # ─────────────────────────────────────────────────────────────────────────
    # PUSH CODE — Commits a generated code file to a branch
    # ─────────────────────────────────────────────────────────────────────────

    def _push_code(self, payload: dict) -> dict:
        """
        Pushes a generated code file to a specific branch.
        payload: {branch_name, filepath, content, commit_message}
        """
        branch_name    = payload["branch_name"]
        filepath       = payload["filepath"]
        content        = payload["content"]
        commit_message = payload.get("commit_message", f"Add {filepath}")

        repo = self._get_repo()
        self.log.info(f"Pushing '{filepath}' to branch '{branch_name}'...")

        try:
            existing = repo.get_contents(filepath, ref=branch_name)
            result   = repo.update_file(filepath, commit_message, content,
                                        existing.sha, branch=branch_name)
            action   = "updated"
        except UnknownObjectException:
            result  = repo.create_file(filepath, commit_message, content,
                                       branch=branch_name)
            action  = "created"

        url = result["content"].html_url
        self.log.success(f"Code {action} → {url}")
        return {"filepath": filepath, "branch": branch_name, "url": url, "action": action}

    # ─────────────────────────────────────────────────────────────────────────
    # CREATE PR — Opens a pull request from feature branch → main
    # ─────────────────────────────────────────────────────────────────────────

    def _create_pr(self, payload: dict) -> dict:
        """
        Creates a Pull Request from feature branch to main.
        payload: {branch_name, title, body}
        Returns PR URL and PR number.
        """
        branch_name = payload["branch_name"]
        title       = payload.get("title", f"PR from {branch_name}")
        body        = payload.get("body", "")

        repo = self._get_repo()
        self.log.info(f"Creating PR: '{title}'...")

        try:
            base = repo.get_branch("main")
            base_name = "main"
        except Exception:
            base_name = "master"

        pr = repo.create_pull(
            title=title,
            body=body,
            head=branch_name,
            base=base_name
        )
        self.log.success(f"PR created → {pr.html_url}")
        return {
            "pr_url":    pr.html_url,
            "pr_number": pr.number,
            "title":     pr.title,
            "branch":    branch_name,
            "message":   f"Pull request created: {pr.html_url}"
        }

    # ─────────────────────────────────────────────────────────────────────────
    # CODE REVIEW — Claude reviews code and returns structured feedback
    # ─────────────────────────────────────────────────────────────────────────

    def _code_review(self, payload: dict) -> dict:
        """
        Sends code to Claude for review. Returns structured feedback.
        payload: {code, filename, ticket_summary}

        Review covers:
          - Overall assessment
          - Code quality issues
          - Security concerns
          - Suggestions for improvement
          - Score out of 10
        """
        code           = payload.get("code", "")
        filename       = payload.get("filename", "code.py")
        ticket_summary = payload.get("ticket_summary", "")

        self.log.thinking(f"Claude reviewing '{filename}'...")

        system = """You are a senior software engineer performing a code review.
Analyze the code and return a JSON object with this exact structure:
{
  "overall": "string — 1-2 sentence overall assessment",
  "score": 7,
  "quality_issues": ["issue 1", "issue 2"],
  "security_concerns": ["concern 1"],
  "suggestions": ["suggestion 1", "suggestion 2"],
  "positive_aspects": ["good thing 1"]
}
Return ONLY valid JSON. No markdown fences."""

        user_msg = f"""Review this code written for ticket: "{ticket_summary}"

File: {filename}

```
{code[:8000]}
```"""

        response = self._llm.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1500,
            system=system,
            messages=[{"role": "user", "content": user_msg}]
        )

        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        try:
            review = json.loads(raw)
        except Exception:
            review = {
                "overall": raw[:300],
                "score": 0,
                "quality_issues": [],
                "security_concerns": [],
                "suggestions": [],
                "positive_aspects": []
            }

        self.log.success(f"Code review complete — score: {review.get('score')}/10")

        # Format as a readable JIRA comment
        review["jira_comment"] = self._format_review_as_comment(review, filename)
        return review

    @staticmethod
    def _format_review_as_comment(review: dict, filename: str) -> str:
        """Formats the code review dict as a readable JIRA comment."""
        lines = [
            f"*Code Review — {filename}*",
            f"Score: {review.get('score', '?')}/10",
            "",
            f"*Overall:* {review.get('overall', '')}",
        ]
        if review.get("positive_aspects"):
            lines += ["", "*What's Good:*"]
            lines += [f"- {p}" for p in review["positive_aspects"]]
        if review.get("quality_issues"):
            lines += ["", "*Quality Issues:*"]
            lines += [f"- {i}" for i in review["quality_issues"]]
        if review.get("security_concerns"):
            lines += ["", "*Security Concerns:*"]
            lines += [f"- {c}" for c in review["security_concerns"]]
        if review.get("suggestions"):
            lines += ["", "*Suggestions:*"]
            lines += [f"- {s}" for s in review["suggestions"]]
        return "\n".join(lines)

    # ─────────────────────────────────────────────────────────────────────────
    # HELPERS — Markdown formatter
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def format_summary_as_markdown(summary: dict) -> str:
        """
        Converts a TechnicalSummary dict into a well-formatted Markdown file.
        This is what gets committed to GitHub.
        """
        lines = [
            f"# {summary.get('title', 'YouTube Technical Summary')}",
            "",
            "## Overview",
            "",
            summary.get("overview", ""),
            "",
            "## Key Points",
            "",
        ]

        for point in summary.get("key_points", []):
            lines.append(f"- {point}")

        lines += ["", "## Technical Concepts", ""]
        concepts = summary.get("technical_concepts", [])
        lines.append(", ".join(f"`{c}`" for c in concepts) if concepts else "_None identified_")

        lines += ["", "## Tools & Libraries Mentioned", ""]
        tools = summary.get("tools_mentioned", [])
        lines.append(", ".join(f"`{t}`" for t in tools) if tools else "_None identified_")

        code_snippets = summary.get("code_snippets", [])
        if code_snippets:
            lines += ["", "## Code Examples Discussed", ""]
            for snippet in code_snippets:
                lines.append(f"- {snippet}")

        lines += [
            "",
            "---",
            "",
            "_Summary generated by [YouTube ↔ GitHub AI Orchestrator](https://github.com) "
            "powered by Claude Sonnet 4.6_"
        ]

        return "\n".join(lines)
