"""
agents/github_agent.py
──────────────────────
GitHub Agent — pushes and fetches files from your GitHub repository.

FLOW (push):
  1. Authenticate with GitHub PAT
  2. Get or create the target repository
  3. Convert summary dict → formatted Markdown
  4. Create/update file in repo with commit message
  5. Return GitHub URL of the pushed file

FLOW (fetch):
  1. Authenticate
  2. Get repo
  3. Fetch file content by filename
  4. Return content to Orchestrator
"""

import os
import base64
from datetime import datetime
from github import Github, GithubException, UnknownObjectException
from tenacity import retry, stop_after_attempt, wait_exponential

from agents.base_agent import BaseAgent
from models.schemas import Task, GitHubPushInput, GitHubFetchInput, GitHubResult
from orchestrator.memory import Memory


class GitHubAgent(BaseAgent):
    """
    Handles all GitHub operations:
      - Create repo if it doesn't exist
      - Push markdown summary files
      - Fetch files by name
      - List all files in the repo
    """

    def __init__(self, memory: Memory):
        super().__init__(memory)
        token    = os.getenv("GITHUB_TOKEN")
        username = os.getenv("GITHUB_USERNAME")
        repo     = os.getenv("GITHUB_REPO_NAME", "youtube-summaries")

        if not token or not username:
            raise EnvironmentError("GITHUB_TOKEN and GITHUB_USERNAME must be set in .env")

        self._github   = Github(token)
        self._username = username
        self._repo_name = repo
        self._repo     = None   # Lazy-loaded on first use

    @property
    def name(self) -> str:
        return "GitHub Agent"

    # ─────────────────────────────────────────────────────────────────────────
    # MAIN ENTRY POINT (called by BaseAgent.run)
    # ─────────────────────────────────────────────────────────────────────────

    def _execute(self, task: Task) -> dict:
        """
        Routes to push or fetch based on task.action.
        task.action = "push"  → push a summary file to GitHub
        task.action = "fetch" → retrieve a file from GitHub
        task.action = "list"  → list all files in the repo
        """
        action = task.action.lower()

        if action == "push":
            return self._push(task.payload)
        elif action == "fetch":
            return self._fetch(task.payload)
        elif action == "list":
            return self._list_files()
        else:
            raise ValueError(f"Unknown GitHub action: '{action}'. Use push, fetch, or list.")

    # ─────────────────────────────────────────────────────────────────────────
    # REPO — Get or create
    # ─────────────────────────────────────────────────────────────────────────

    def _get_repo(self):
        """
        Returns the GitHub repo object.
        Creates the repo if it doesn't exist.
        Uses lazy loading — only connects to GitHub when first needed.
        """
        if self._repo:
            return self._repo

        user = self._github.get_user()
        try:
            self._repo = user.get_repo(self._repo_name)
            self.log.info(f"Connected to repo '{self._username}/{self._repo_name}'")
        except UnknownObjectException:
            self.log.warning(f"Repo '{self._repo_name}' not found — creating it...")
            self._repo = user.create_repo(
                self._repo_name,
                description="YouTube video technical summaries — generated by AI Orchestrator",
                private=False,
                auto_init=True   # Creates with a default README so it's not empty
            )
            self.log.success(f"Repo created → https://github.com/{self._username}/{self._repo_name}")

        return self._repo

    # ─────────────────────────────────────────────────────────────────────────
    # PUSH — Create or update a file in GitHub
    # ─────────────────────────────────────────────────────────────────────────

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=5))
    def _push(self, payload: dict) -> dict:
        """
        Pushes a summary file to GitHub.
        If the file already exists (same video re-processed), updates it.

        payload keys: filename, content, commit_message
        """
        inp = GitHubPushInput(**payload)
        repo = self._get_repo()

        self.log.info(f"Pushing '{inp.filename}' to GitHub...")

        try:
            # File exists — update it
            existing = repo.get_contents(inp.filename)
            result = repo.update_file(
                path=inp.filename,
                message=inp.commit_message,
                content=inp.content,
                sha=existing.sha       # Required by GitHub API for updates
            )
            action_done = "updated"

        except UnknownObjectException:
            # File doesn't exist — create it
            result = repo.create_file(
                path=inp.filename,
                message=inp.commit_message,
                content=inp.content
            )
            action_done = "created"

        github_url = result["content"].html_url
        self.log.success(f"File {action_done} → {github_url}")

        return GitHubResult(
            success=True,
            action="pushed",
            filename=inp.filename,
            url=github_url,
            message=f"File {action_done} successfully at {github_url}"
        ).model_dump()

    # ─────────────────────────────────────────────────────────────────────────
    # FETCH — Retrieve a file from GitHub
    # ─────────────────────────────────────────────────────────────────────────

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=5))
    def _fetch(self, payload: dict) -> dict:
        """
        Fetches a file's content from GitHub by filename.
        payload keys: filename
        """
        inp = GitHubFetchInput(**payload)
        repo = self._get_repo()

        self.log.info(f"Fetching '{inp.filename}' from GitHub...")

        try:
            file_obj = repo.get_contents(inp.filename)
            # GitHub returns content as base64 — decode it
            content = base64.b64decode(file_obj.content).decode("utf-8")
            self.log.success(f"File fetched — {len(content)} characters")

            return GitHubResult(
                success=True,
                action="fetched",
                filename=inp.filename,
                url=file_obj.html_url,
                content=content,
                message=f"File fetched from {file_obj.html_url}"
            ).model_dump()

        except UnknownObjectException:
            raise FileNotFoundError(
                f"File '{inp.filename}' not found in repo '{self._repo_name}'"
            )

    # ─────────────────────────────────────────────────────────────────────────
    # LIST — Show all files in the repo
    # ─────────────────────────────────────────────────────────────────────────

    def _list_files(self) -> dict:
        """Returns a list of all files in the root of the repo."""
        repo = self._get_repo()
        contents = repo.get_contents("")
        files = [
            {"name": f.name, "url": f.html_url, "size_bytes": f.size}
            for f in contents
            if f.type == "file"
        ]
        self.log.success(f"Found {len(files)} file(s) in repo")
        return {"files": files, "count": len(files)}

    # ─────────────────────────────────────────────────────────────────────────
    # HELPERS — Markdown formatter
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def format_summary_as_markdown(summary: dict) -> str:
        """
        Converts a TechnicalSummary dict into a well-formatted Markdown file.
        This is what gets committed to GitHub.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# {summary.get('title', 'YouTube Technical Summary')}",
            "",
            f"> **Generated:** {now}  ",
            f"> **Source:** {summary.get('video_url', '')}  ",
            f"> **Difficulty:** {summary.get('difficulty_level', '—')}  ",
            f"> **Target Audience:** {summary.get('target_audience', '—')}  ",
            f"> **Transcript Words:** {summary.get('transcript_length', 0):,}",
            "",
            "---",
            "",
            "## Overview",
            "",
            summary.get("overview", ""),
            "",
            "## Key Points",
            "",
        ]

        for point in summary.get("key_points", []):
            lines.append(f"- {point}")

        lines += ["", "## Technical Concepts", ""]
        concepts = summary.get("technical_concepts", [])
        lines.append(", ".join(f"`{c}`" for c in concepts) if concepts else "_None identified_")

        lines += ["", "## Tools & Libraries Mentioned", ""]
        tools = summary.get("tools_mentioned", [])
        lines.append(", ".join(f"`{t}`" for t in tools) if tools else "_None identified_")

        code_snippets = summary.get("code_snippets", [])
        if code_snippets:
            lines += ["", "## Code Examples Discussed", ""]
            for snippet in code_snippets:
                lines.append(f"- {snippet}")

        lines += [
            "",
            "---",
            "",
            "_Summary generated by [YouTube ↔ GitHub AI Orchestrator](https://github.com) "
            "powered by Claude Sonnet 4.6_"
        ]

        return "\n".join(lines)
